CREATE TABLE order_rows (
  id SERIAL PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id),
  order_art_id INTEGER REFERENCES order_articles(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)