CREATE TABLE order_articles (
  id SERIAL PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  price NUMERIC(9,3) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
)